language: ru

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "LanguageModelFeaturizer"
  model_name: "bert"
  model_weights: "bert-base-cased"
  cache_dir: null

- name: DIETClassifier
  epochs: 3000
  transformer_size: 32
  number_of_transformer_layers: 10
  use_masked_language_model: false
  batch_strategy: "balanced"
  hidden_layers_sizes:
    text: [32]

- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 3000

policies:
- name: MemoizationPolicy
  max_history: 10
- name: RulePolicy
- name: TEDPolicy
  max_history: 10
  epochs: 3000
  constrain_similarities: true
assistant_id: 20241116-183117-chromatic-buyer
